import { z } from 'zod';
import { GameSchema } from '../index.js';
import { LangSchema } from './catalog.js';
import { CurrencySchema } from './me.js';
import { PriceSourceSchema } from './prices.js';

// The collection (`/collection/**`, VB-31): binders, the have list and the wish list of the
// signed-in user. Rows carry a client-generated `id` and `updatedAt`, so the sync engine
// (`/sync/**`) uses the same tables; a delete removes the row (VB-75).

/** Page size of `GET /collection/entries` and `GET /collection/wishlist`. */
export const COLLECTION_PAGE_SIZE = 50;

/** Card conditions, best first; the price factor of MT and of EX and worse is an estimate. */
export const CollectionConditionSchema = z.enum(['MT', 'NM', 'EX', 'GD', 'LP', 'PL', 'PO']);
export type CollectionCondition = z.infer<typeof CollectionConditionSchema>;

export const FinishSchema = z.string().trim().min(1).max(32);
const NoteSchema = z.string().trim().max(500);
const Cents = z.number().int().min(0).max(100_000_000);
const Timestamp = z.iso.datetime({ offset: true });

// ---- Binders ----

export const BinderSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  game: GameSchema.nullable(),
  position: z.number().int(),
  colour: z.string().nullable(),
  createdAt: Timestamp,
  updatedAt: Timestamp,
});
export type Binder = z.infer<typeof BinderSchema>;

export const BindersResponseSchema = z.object({ binders: z.array(BinderSchema) });
export type BindersResponse = z.infer<typeof BindersResponseSchema>;

const BinderFields = {
  name: z.string().trim().min(1).max(60),
  game: GameSchema.nullable(),
  colour: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/)
    .nullable(),
};

/** `POST /collection/binders`; `id` is the client's (generated by the server when absent). */
export const CreateBinderRequestSchema = z.strictObject({
  id: z.uuid().optional(),
  name: BinderFields.name,
  game: BinderFields.game.optional(),
  colour: BinderFields.colour.optional(),
});
export type CreateBinderRequest = z.infer<typeof CreateBinderRequestSchema>;

/** `PATCH /collection/binders/:id`. */
export const UpdateBinderRequestSchema = z
  .strictObject({
    name: BinderFields.name,
    game: BinderFields.game,
    colour: BinderFields.colour,
  })
  .partial();
export type UpdateBinderRequest = z.infer<typeof UpdateBinderRequestSchema>;

/** `PUT /collection/binders/order`: every live binder id, in the new order. */
export const BinderOrderRequestSchema = z.strictObject({
  ids: z.array(z.uuid()).max(500),
});
export type BinderOrderRequest = z.infer<typeof BinderOrderRequestSchema>;

// ---- Entries ----

/** The print an entry points at, with what the list shows. */
export const EntryPrintSchema = z.object({
  id: z.uuid(),
  cardId: z.uuid(),
  game: GameSchema,
  setCode: z.string(),
  setName: z.string(),
  number: z.string(),
  /** Name in the entry's language, else English. */
  name: z.string(),
  rarity: z.string().nullable(),
  finishes: z.array(z.string()),
  imageUrl: z.url().nullable(),
});
export type EntryPrint = z.infer<typeof EntryPrintSchema>;

/**
 * The current price of one copy: the market price (near mint) of the entry's finish (else the
 * print's `normal`) from the source the currency prefers, times the condition factor.
 */
export const EntryPriceSchema = z.object({
  source: PriceSourceSchema,
  finish: z.string(),
  currency: CurrencySchema,
  /** Near-mint market price. */
  marketCents: z.number().int(),
  /** Condition factor; anything but NM is an estimate. */
  factor: z.number(),
  /** One copy in the entry's condition. */
  unitCents: z.number().int(),
  observedAt: Timestamp,
});
export type EntryPrice = z.infer<typeof EntryPriceSchema>;

export const CollectionEntrySchema = z.object({
  id: z.uuid(),
  printId: z.uuid(),
  binderId: z.uuid().nullable(),
  quantity: z.number().int().min(1),
  language: z.string(),
  condition: CollectionConditionSchema,
  finish: z.string(),
  purchasePriceCents: z.number().int().nullable(),
  purchaseCurrency: CurrencySchema.nullable(),
  note: z.string().nullable(),
  createdAt: Timestamp,
  updatedAt: Timestamp,
  print: EntryPrintSchema,
  /** null without a price. */
  price: EntryPriceSchema.nullable(),
});
export type CollectionEntry = z.infer<typeof CollectionEntrySchema>;

const EntryFields = {
  printId: z.uuid(),
  binderId: z.uuid().nullable(),
  quantity: z.number().int().min(1).max(9999),
  language: LangSchema,
  condition: CollectionConditionSchema,
  finish: FinishSchema,
  purchasePriceCents: Cents.nullable(),
  purchaseCurrency: CurrencySchema.nullable(),
  note: NoteSchema.nullable(),
};

/** One new entry; `id` is the client's, so a retried POST adds nothing twice. */
export const NewEntrySchema = z.strictObject({
  id: z.uuid().optional(),
  printId: EntryFields.printId,
  binderId: EntryFields.binderId.optional(),
  quantity: EntryFields.quantity.default(1),
  language: EntryFields.language.default('en'),
  condition: EntryFields.condition.default('NM'),
  finish: EntryFields.finish.default('normal'),
  purchasePriceCents: EntryFields.purchasePriceCents.optional(),
  purchaseCurrency: EntryFields.purchaseCurrency.optional(),
  note: EntryFields.note.optional(),
});
export type NewEntry = z.input<typeof NewEntrySchema>;
/** A new entry after validation, defaults applied. */
export type NewEntryData = z.output<typeof NewEntrySchema>;

/** `POST /collection/entries`: one entry or up to 500. */
export const CreateEntriesRequestSchema = z.union([
  NewEntrySchema,
  z.array(NewEntrySchema).min(1).max(500),
]);
export type CreateEntriesRequest = z.input<typeof CreateEntriesRequestSchema>;

/** `PATCH /collection/entries/:id`: any subset of the editable fields. */
export const UpdateEntryRequestSchema = z
  .strictObject({
    binderId: EntryFields.binderId,
    quantity: EntryFields.quantity,
    language: EntryFields.language,
    condition: EntryFields.condition,
    finish: EntryFields.finish,
    purchasePriceCents: EntryFields.purchasePriceCents,
    purchaseCurrency: EntryFields.purchaseCurrency,
    note: EntryFields.note,
  })
  .partial();
export type UpdateEntryRequest = z.infer<typeof UpdateEntryRequestSchema>;

/** `GET /collection/entries?binder=&game=&set=&condition=&lang=&q=&page=&currency=`. */
export const EntriesQuerySchema = z.object({
  /** A binder id, or `none` for entries in no binder. */
  binder: z.union([z.uuid(), z.literal('none')]).optional(),
  game: GameSchema.optional(),
  /** Set code. */
  set: z.string().trim().min(1).max(32).optional(),
  condition: CollectionConditionSchema.optional(),
  lang: LangSchema.optional(),
  /** Card name (any language), or a collector number. */
  q: z.string().trim().min(1).max(100).optional(),
  page: z.coerce.number().int().min(1).max(10_000).default(1),
  /** Picks the price source (EUR → Cardmarket first); the user's currency by default. */
  currency: CurrencySchema.optional(),
});
export type EntriesQuery = z.infer<typeof EntriesQuerySchema>;

export const EntriesResponseSchema = z.object({
  entries: z.array(CollectionEntrySchema),
  page: z.number().int(),
  pageSize: z.number().int(),
  total: z.number().int(),
});
export type EntriesResponse = z.infer<typeof EntriesResponseSchema>;

/** `POST /collection/entries` (201): the entries as stored. */
export const CreateEntriesResponseSchema = z.object({ entries: z.array(CollectionEntrySchema) });
export type CreateEntriesResponse = z.infer<typeof CreateEntriesResponseSchema>;

// ---- Wish list ----

export const WishlistEntrySchema = z.object({
  id: z.uuid(),
  printId: z.uuid(),
  quantity: z.number().int().min(1),
  /** null: any language. */
  language: z.string().nullable(),
  /** null: any finish. */
  finish: z.string().nullable(),
  /** null: any condition; else the worst one accepted. */
  minCondition: CollectionConditionSchema.nullable(),
  maxPriceCents: z.number().int().nullable(),
  currency: CurrencySchema.nullable(),
  note: z.string().nullable(),
  createdAt: Timestamp,
  updatedAt: Timestamp,
  print: EntryPrintSchema,
  /** The price of one copy in `minCondition` (NM when unset); null without a price. */
  price: EntryPriceSchema.nullable(),
});
export type WishlistEntry = z.infer<typeof WishlistEntrySchema>;

const WishFields = {
  quantity: EntryFields.quantity,
  language: LangSchema.nullable(),
  finish: FinishSchema.nullable(),
  minCondition: CollectionConditionSchema.nullable(),
  maxPriceCents: Cents.nullable(),
  currency: CurrencySchema.nullable(),
  note: NoteSchema.nullable(),
};

export const NewWishSchema = z.strictObject({
  id: z.uuid().optional(),
  printId: z.uuid(),
  quantity: WishFields.quantity.default(1),
  language: WishFields.language.optional(),
  finish: WishFields.finish.optional(),
  minCondition: WishFields.minCondition.optional(),
  maxPriceCents: WishFields.maxPriceCents.optional(),
  currency: WishFields.currency.optional(),
  note: WishFields.note.optional(),
});
export type NewWish = z.input<typeof NewWishSchema>;
export type NewWishData = z.output<typeof NewWishSchema>;

/** `POST /collection/wishlist`: one wish or up to 500. */
export const CreateWishesRequestSchema = z.union([
  NewWishSchema,
  z.array(NewWishSchema).min(1).max(500),
]);
export type CreateWishesRequest = z.input<typeof CreateWishesRequestSchema>;

export const UpdateWishRequestSchema = z.strictObject(WishFields).partial();
export type UpdateWishRequest = z.infer<typeof UpdateWishRequestSchema>;

/** `GET /collection/wishlist?game=&q=&page=&currency=`. */
export const WishlistQuerySchema = EntriesQuerySchema.pick({
  game: true,
  set: true,
  q: true,
  page: true,
  currency: true,
});
export type WishlistQuery = z.infer<typeof WishlistQuerySchema>;

export const WishlistResponseSchema = z.object({
  entries: z.array(WishlistEntrySchema),
  page: z.number().int(),
  pageSize: z.number().int(),
  total: z.number().int(),
});
export type WishlistResponse = z.infer<typeof WishlistResponseSchema>;

export const CreateWishesResponseSchema = z.object({ entries: z.array(WishlistEntrySchema) });
export type CreateWishesResponse = z.infer<typeof CreateWishesResponseSchema>;

// ---- Summary, owned ----

/** A sum in one currency from one source, with the oldest observation that went into it. */
export const ValueTotalSchema = z.object({
  source: PriceSourceSchema,
  currency: CurrencySchema,
  cents: z.number().int(),
  observedAt: Timestamp,
});
export type ValueTotal = z.infer<typeof ValueTotalSchema>;

export const ValueGroupSchema = z.object({
  /** Copies (sum of quantities). */
  cards: z.number().int(),
  entries: z.number().int(),
  totals: z.array(ValueTotalSchema),
  /** Copies without a price. */
  unpriced: z.number().int(),
});
export type ValueGroup = z.infer<typeof ValueGroupSchema>;

/** `GET /collection/summary?currency=`: the value panel, the binder sidebar and the tab counts. */
export const CollectionSummarySchema = z.object({
  collection: ValueGroupSchema.extend({
    /** True when a condition factor other than NM went into the value. */
    estimate: z.boolean(),
    games: z.array(ValueGroupSchema.extend({ game: GameSchema })),
    /** Per binder id; `null` is the entries in no binder. */
    binders: z.array(ValueGroupSchema.extend({ binderId: z.uuid().nullable() })),
  }),
  wishlist: ValueGroupSchema.extend({
    games: z.array(ValueGroupSchema.extend({ game: GameSchema })),
    /** Wishes whose current price is at or under the wish price (same currency). */
    inBudget: z.number().int(),
  }),
});
export type CollectionSummary = z.infer<typeof CollectionSummarySchema>;

export const SummaryQuerySchema = EntriesQuerySchema.pick({ currency: true });

/**
 * `GET /collection/owned?printIds=a,b,…` (up to 200, the card page) or `?game=&set=` (every print
 * of a set, the set page): copies per print.
 */
export const OwnedQuerySchema = z.union([
  z.object({
    printIds: z
      .string()
      .transform((s) => s.split(',').filter(Boolean))
      .pipe(z.array(z.uuid()).min(1).max(200)),
  }),
  z.object({ game: GameSchema, set: z.string().trim().min(1).max(32) }),
]);
export type OwnedQuery = z.infer<typeof OwnedQuerySchema>;

export const OwnedResponseSchema = z.object({
  /** Print id → copies owned; prints without a copy are absent. */
  owned: z.record(z.string(), z.number().int()),
  /** Print id → finish → copies, for the prints in `owned`. */
  byFinish: z.record(z.string(), z.record(z.string(), z.number().int())),
  /** Print id → wishes; prints without a wish are absent. */
  wished: z.record(z.string(), z.number().int()),
});
export type OwnedResponse = z.infer<typeof OwnedResponseSchema>;
